return {
	{ "navarasu/onedark.nvim", priority = 999 },
	{ "sainnhe/edge", priority = 999 },
	{ "sainnhe/sonokai", priority = 999 },
	{ "sainnhe/gruvbox-material", priority = 999 },
	{ "shaunsingh/nord.nvim", priority = 999 },
	{ "sainnhe/everforest", priority = 999 },
	{ "EdenEast/nightfox.nvim", priority = 999 },
	{ "rebelot/kanagawa.nvim", priority = 999 },
	{ "catppuccin/nvim", as = "catppuccin", priority = 999 },
	{ "rose-pine/neovim", as = "rose-pine", priority = 999 },
	{ "olimorris/onedarkpro.nvim", priority = 999 },
	{ "tanvirtin/monokai.nvim", priority = 999 },
	{ "marko-cerovac/material.nvim", priority = 999 },
}
